name: Collect Allure environment data (short version)
description: Collects environment data and puts them into allure-results folder
runs:
  using: 'composite'
  steps:
    - run: |
        pwd

        ENV_PROP_FILE="environment.properties"

        export $(grep -v '^#' .env | xargs)
        echo "PROXY_URL=$PROXY_URL" > $ENV_PROP_FILE

        function writeData() {
          echo "writeData input_data=$1"
          echo "writeData URL=$2"
          RESULT=$(curl -X POST -H 'Content-Type: application/json' -d $1 $2)
          echo "writeData result1=$RESULT"
          RESULT=$(echo $RESULT | sed 's/\"/\\\"/g')
          echo "writeData result2=$RESULT"
          echo "$3=$RESULT" >> $ENV_PROP_FILE
        }

        # EVM version
        writeData '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":0}' $PROXY_URL 'EVM.Version'

        # Proxy version
        writeData '{"jsonrpc":"2.0","method":"neon_proxy_version","params":[],"id":0}' $PROXY_URL 'Proxy.Version'

        # NEON Cli version
        writeData '{"jsonrpc":"2.0","method":"neon_cli_version","params":[],"id":0}' $PROXY_URL 'NEON-CLI.Version'

        # Solana cluster version
        # SOLANA_VERSION=$(curl $SOLANA_URL -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","id":1, "method":"getVersion"}')
        # writeData '{"jsonrpc":"2.0","id":1,"method":"getVersion"}' $SOLANA_URL 'Solana.Version'

        echo "Solana.Explorer=$SOLANA_EXPLORER" >> $ENV_PROP_FILE

        cat $ENV_PROP_FILE

        ALLURE_RESULTS="allure-results"
        cp "./$ENV_PROP_FILE" "report/$ALLURE_RESULTS"
        echo "there are now files in report/$ALLURE_RESULTS"
        ls "report/$ALLURE_RESULTS"
        cp "./$ENV_PROP_FILE" ./report
        # mkdir $ALLURE_RESULTS
        cp "./$ENV_PROP_FILE" "./$ALLURE_RESULTS"

        cat "./report/$ENV_PROP_FILE"
      shell: bash
