name: Check Solana
description: Checking Solana availability via CLI
runs:
  using: "composite"
  steps:
    - run: |
        sh -c "$(curl -sSfL https://release.solana.com/v1.8.5/install)"
        echo "solana --version"
        solana --version
      shell: bash
