name: JDK 16

on:
  push:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
        required: false
      network:
        description: 'Network (devnet, testnet, internal.testnet, neonswap.live, aws, ropsten, rinkeby)'
        required: true
        default: 'devnet'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

  jdk:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/allure-prep
      - uses: ./.github/actions/switch-network
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        if: always()
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Run check style
        uses: nikitasavinov/checkstyle-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-pr-check'
          tool_name: 'testtool'
      - name: Gradle wrapper
        if: always()
        run: gradle wrapper --gradle-version 7.2
      - name: Print Gradle version
        if: always()
        run: gradle --version
      - name: Grant execute permission for gradlew
        if: always()
        run: chmod +x gradlew
      - name: Test
        timeout-minutes: 15
        if: always()
        run: ./gradlew build --warning-mode all
      - uses: ./.github/actions/allure-upload
        if: always()
        with:
          folder-name: report/allure-results
