name: Python 3.8, Node.js 16, allure

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     # ruby-version: ['2.6', '2.7', '3.0']
    #     ruby-version: ['2.7']
    #     # node-version: [10.x, 12.x, 14.x, 15.x, 16.x]
    #     node-version: [16.x]

    steps:
    - uses: actions/checkout@v2

  python:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/allure-prep
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        flake8 .
    - name: Test with pytest
      if: always()
      run: |
        pwd
        pytest --alluredir=allure-results
#     - name: Analysing the code with pylint
#       run: |
#         pylint `ls -R|grep .py$|xargs`

    - name: Look at Allure
      if: always()
      uses: ./.github/actions/allure-show

    # TODO: de-duplicate
    - name: Archive Allure results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: allure-results
        path: allure-results
    # - name: Archive Allure reports
    #   if: always()
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: allure-reports
    #     path: allure-reports

  node:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        # node-version: [10.x, 12.x, 14.x, 15.x, 16.x]
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/allure-prep
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      if: always()
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    # - run: find -name '*.test.js' | while read test ; do echo $test ; npm test $test ; done

    - name: Look at Allure
      if: always()
      uses: ./.github/actions/allure-show

    # TODO: de-duplicate
    - name: Archive Allure results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: allure-results
        path: allure-results
    # - name: Archive Allure reports
    #   if: always()
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: allure-reports
    #     path: allure-reports

  allure:
    runs-on: ubuntu-latest
    if: always()
    needs:
      # - build
      - python
      - node
    steps:

    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v2

    - name: Get Allure history
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Allure Report with history
      uses: simple-elf/allure-report-action@v1.5
      if: always()

    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@master
      if: always()
      #id: allure-report
      with:
        allure_results: allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history
        keep_reports: 50

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history
